FROM node:15
WORKDIR /app
# COPY package.json /app   is same as COPY package.json .
# it means copy package.json into /app
COPY ../../../app/product-service/package.json /app
RUN npm install
COPY ./product-service  /app
ENV PORT 4001
EXPOSE $PORT
CMD ["node", "index.js"]