services:
  order-service:
    build: 
      context: ./
      dockerfile: Dockerfile.order-service
    networks:
      - micro-service-network
    ports:
      - "4004:4002"
    restart: always
    env_file:
      - ./.env
    # volumes:
    # - persist_volume:/app
    
    depends_on:
      - product-service
  product-service:
    build: 
      context: ./
      dockerfile: Dockerfile.product-service
    networks:
      - micro-service-network
    ports:
      - "4001:4001"
    restart: always
    # volumes:
    #   - persist_volume:/app

  # nginx:
  #   image: nginx
  #   ports:
  #     - "80:80"  # Expose NGINX on the public network
  #   # volumes:
  #   #   - ./nginx.conf:/etc/nginx/nginx.conf
  #   # networks:
  #   #   - my-private-network

networks:
  micro-service-network:
    driver: bridge